# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171016_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinprices',
            name='name',
            field=models.CharField(default=False, max_length=15),
        ),
    ]
