# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180210_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinprices',
            name='sentiment_score',
            field=models.FloatField(default=10.0, max_length=10),
            preserve_default=False,
        ),
    ]
