# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_coinprices_sentiment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=15)),
                ('usd_balance', models.FloatField(max_length=10)),
                ('btc_balance', models.FloatField(max_length=10)),
                ('ltc_balance', models.FloatField(max_length=10)),
                ('eth_balance', models.FloatField(max_length=10)),
                ('gbp_balance', models.FloatField(max_length=10)),
            ],
        ),
    ]
