# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20180205_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinprices',
            name='five_day_predictions',
        ),
        migrations.RemoveField(
            model_name='coinprices',
            name='predictions',
        ),
    ]
