# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinprices',
            name='image',
        ),
    ]
