# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_coinprices_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinprices',
            name='trend',
            field=models.CharField(default=False, max_length=15),
        ),
    ]
