# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171016_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprices',
            name='current_price',
            field=models.FloatField(default=100),
        ),
    ]
