# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180202_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprices',
            name='predictions',
            field=models.CharField(max_length=100000),
        ),
    ]
