# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_coinprices_five_day_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprices',
            name='predictions',
            field=models.FloatField(max_length=10),
        ),
    ]
