# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_coinprices_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gbp_balance',
            new_name='eur_balance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
